# Customer briefs Grace collected this quarter (all companies are fictional).
BRIEFS = [
    {
        "customer": "Fenwick Outdoor",
        "job": "resolve_customer_requests",
        "users": "customers",
        "inputs": ["chat", "email", "web_form"],
        "daily_volume": 6500,
        "latency": "interactive",
        "platform": "anthropic_api",
        "write_actions": [
            {"name": "create_return", "reversible": True, "max_usd": 0},
            {"name": "issue_refund", "reversible": False, "max_usd": 250},
        ],
        "labelled_examples": 800,
    },
    {
        "customer": "Ostrava Re",
        "job": "extract_from_documents",
        "users": "back_office",
        "inputs": ["pdf", "scans", "email_attachments"],
        "daily_volume": 9000,
        "review_capacity_per_day": 900,
        "latency": "overnight",
        "platform": "bedrock",
        "write_actions": [{"name": "post_claim_fields", "reversible": True, "max_usd": 0}],
        "labelled_examples": 2000,
        "needs_structured_output": True,
    },
    {
        "customer": "Halden Pharma",
        "job": "answer_employee_questions",
        "users": "employees",
        "inputs": ["wiki", "policies", "shared_drives"],
        "daily_volume": 4000,
        "latency": "interactive",
        "platform": "vertex",
        "per_user_permissions": True,
        "acl_sync_in_scope": False,
        "write_actions": [{"name": "file_it_ticket", "reversible": True, "max_usd": 0}],
        "labelled_examples": 300,
        "needs_citations": True,
        "needs_structured_output": True,
    },
    {
        "customer": "Quayside Bank",
        "job": "assist_developers",
        "users": "developers",
        "inputs": ["repos", "pull_requests", "ci_logs"],
        "daily_volume": 450,
        "latency": "minutes",
        "platform": "anthropic_api",
        "agent_can_push": True,
        "branch_protection": True,
        "write_actions": [{"name": "open_pull_request", "reversible": True, "max_usd": 0}],
        "labelled_examples": 40,
    },
    {
        "customer": "Marlow General Hospital",
        "job": "schedule_shifts",
        "users": "employees",
        "inputs": ["wiki", "rosters"],
        "daily_volume": 300,
        "latency": "minutes",
        "platform": "anthropic_api",
        "labelled_examples": 0,
    },
]
